/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.AirplaneDirectory;
import Buisness.FlightDirectory;
import UserInterface.Airplane.addAirplaneJpanel;
import UserInterface.ManageFlightSchedule.CreateFlightSchedule;
import UserInterface.ManageFlightSchedule.ManageFlightSchedule;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patel
 */
public class ManageAirlinersJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJpanel
     */
    private AirlinerDirectory airlinerdirectory;
    private JPanel CardSequenceJpanel;
    private FlightDirectory flightdirectory;
     private AirplaneDirectory airplanedirectory;

    /**
     *
     * 
     */
    public ManageAirlinersJpanel(JPanel CardSequenceJpanel , AirlinerDirectory airlinerdirectory) {
        initComponents();
       this.CardSequenceJpanel=CardSequenceJpanel;
        this.airlinerdirectory =airlinerdirectory;
        this.flightdirectory=new FlightDirectory();
       // this.airplanedirectory = airplanedirectory;
        PopulateTable();
        
    }

   public void PopulateTable(){
       
        DefaultTableModel dtm = (DefaultTableModel)tblAirliner.getModel();
        dtm.setRowCount(0);
        
         for(Airliner a : airlinerdirectory.getAirlinedirectory()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= a;
            row[1]= a.getAirlinecode();
            row[2]= a.getNumofFlight();
           // row[3] = a.getCountryOperated();
            row[3] = a.getOrigin_country();
            dtm.addRow(row);
        }
   }
   
   public void Populate_search(){
       
       ArrayList<Airliner> list = new ArrayList<>();
       Airliner air = airlinerdirectory.SearchAirliner(txtSearch.getText());
       list.add(air);
       
       DefaultTableModel dtm = (DefaultTableModel)tblAirliner.getModel();
        dtm.setRowCount(0);
        
         for(Airliner a : list){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= a;
            row[1]= a.getAirlinecode();
            row[2]= a.getNumofFlight();
           // row[3] = a.getCountryOperated();
            row[3] = a.getOrigin_country();
            dtm.addRow(row);
        }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirliner = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnManageFlight = new javax.swing.JButton();
        btnAirplane = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(946, 775));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE AIRLINER");

        txtSearch.setBackground(new java.awt.Color(153, 153, 153));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));

        btnsearch.setBackground(new java.awt.Color(153, 153, 153));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        tblAirliner.setBackground(new java.awt.Color(153, 153, 153));
        tblAirliner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Airline_code", "Fleet Size", "Origin Country"
            }
        ));
        jScrollPane1.setViewportView(tblAirliner);

        btnCreate.setBackground(new java.awt.Color(153, 153, 153));
        btnCreate.setText("Create Airliner");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(153, 153, 153));
        btnView.setText("View Airliner");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setText("Delete Airliner");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnManageFlight.setBackground(new java.awt.Color(153, 153, 153));
        btnManageFlight.setText("Manage Flight");
        btnManageFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightActionPerformed(evt);
            }
        });

        btnAirplane.setBackground(new java.awt.Color(153, 153, 153));
        btnAirplane.setText("Add Airplane");
        btnAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirplaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsearch))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCreate)
                                        .addComponent(btnAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(122, 122, 122)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnManageFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnView)
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManageFlight)
                            .addComponent(btnAirplane))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        CardSequenceJpanel.add(new CreateNewAirlinerJpanel(CardSequenceJpanel,airlinerdirectory));
        layout.next(CardSequenceJpanel);
        //CreateNewAirlinerJpanel createpanel = new CreateNewAirlinerJpanel(CardSequenceJpanel,airlinerdirectory);
        //CardSequenceJpanel.add();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnManageFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        CardSequenceJpanel.add(new ManageFlightSchedule(CardSequenceJpanel,airlinerdirectory,flightdirectory));
        layout.next(CardSequenceJpanel);
    }//GEN-LAST:event_btnManageFlightActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblAirliner.getSelectedRow();
        
        if(selectedrow> -1){
            Airliner airliner = airlinerdirectory.getAirlinedirectory().get(selectedrow);
            CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
            CardSequenceJpanel.add(new ViewAirlinerJpanel(CardSequenceJpanel,airliner));
            layout.next(CardSequenceJpanel);
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select Row First");
            return;
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       
       
       
       int selectedRow = tblAirliner.getSelectedRow();
        
        if(selectedRow> -1){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
               
                Airliner airliner = (Airliner)tblAirliner.getValueAt(selectedRow, 0);
                System.out.println(airliner);
                airlinerdirectory.removeAirline(airliner);
                PopulateTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        Populate_search();
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirplaneActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        CardSequenceJpanel.add(new addAirplaneJpanel(CardSequenceJpanel,airlinerdirectory));
        layout.next(CardSequenceJpanel);
    }//GEN-LAST:event_btnAirplaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirplane;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnManageFlight;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirliner;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
