/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.FlightDirectory;
import UserInterface.ManageFlightSchedule.CreateFlightSchedule;
import UserInterface.ManageFlightSchedule.ManageFlightSchedule;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patel
 */
public class ManageAirlinersJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJpanel
     */
    private AirlinerDirectory airlinerdirectory;
    private JPanel CardSequenceJpanel;
    private FlightDirectory flightdirectory;

    /**
     *
     * 
     */
    public ManageAirlinersJpanel(JPanel CardSequenceJpanel , AirlinerDirectory airlinerdirectory) {
        initComponents();
       this.CardSequenceJpanel=CardSequenceJpanel;
        this.airlinerdirectory =airlinerdirectory;
        this.flightdirectory=new FlightDirectory();
        PopulateTable();
        
    }

   public void PopulateTable(){
       
        DefaultTableModel dtm = (DefaultTableModel)tblAirliner.getModel();
        dtm.setRowCount(0);
        
         for(Airliner a : airlinerdirectory.getAirlinedirectory()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= a.getName();
            row[1]= a.getAirlinecode();
            row[2]= a.getNumofFlight();
           // row[3] = a.getCountryOperated();
            row[3] = a.getOrigin_country();
            dtm.addRow(row);
        }
   }
   
   public void Populate_search(){
       
       ArrayList<Airliner> list = new ArrayList<>();
       Airliner air = airlinerdirectory.SearchAirliner(txtSearch.getText());
       list.add(air);
       
       DefaultTableModel dtm = (DefaultTableModel)tblAirliner.getModel();
        dtm.setRowCount(0);
        
         for(Airliner a : list){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= a.getName();
            row[1]= a.getAirlinecode();
            row[2]= a.getNumofFlight();
           // row[3] = a.getCountryOperated();
            row[3] = a.getOrigin_country();
            dtm.addRow(row);
        }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirliner = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnManageFlight = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(946, 775));

        jLabel1.setText("Manage Airliner");

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        tblAirliner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Airline_code", "Fleet Size", "Origin Country"
            }
        ));
        jScrollPane1.setViewportView(tblAirliner);

        btnCreate.setText("Create Airliner");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Airliner");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Airliner");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnManageFlight.setText("Manage Flight");
        btnManageFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnCreate)
                .addGap(130, 130, 130)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnsearch)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnManageFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addComponent(jLabel4)
                .addGap(79, 79, 79)
                .addComponent(btnManageFlight)
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        CardSequenceJpanel.add(new CreateNewAirlinerJpanel(CardSequenceJpanel,airlinerdirectory));
        layout.next(CardSequenceJpanel);
        //CreateNewAirlinerJpanel createpanel = new CreateNewAirlinerJpanel(CardSequenceJpanel,airlinerdirectory);
        //CardSequenceJpanel.add();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnManageFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        CardSequenceJpanel.add(new ManageFlightSchedule(CardSequenceJpanel,airlinerdirectory,flightdirectory));
        layout.next(CardSequenceJpanel);
    }//GEN-LAST:event_btnManageFlightActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblAirliner.getSelectedRow();
        
        if(selectedrow> -1){
            Airliner airliner = airlinerdirectory.getAirlinedirectory().get(selectedrow);
            CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
            CardSequenceJpanel.add(new ViewAirlinerJpanel(CardSequenceJpanel,airliner));
            layout.next(CardSequenceJpanel);
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select Row First");
            return;
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       /* 
        int selectedrow = tblAirliner.getSelectedRow();
        System.out.println(selectedrow);
        
        if(selectedrow >=0){
            
            
            Airliner airliner = (Airliner)tblAirliner.getValueAt(selectedrow,0);
            airlinerdirectory.removeAirline(airliner);
            PopulateTable();
            JOptionPane.showMessageDialog(null, "Deleted successfully");
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }*/
       
       
       int selectedRow = tblAirliner.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airliner airliner = (Airliner)tblAirliner.getValueAt(selectedRow, 0);
                airlinerdirectory.removeAirline(airliner);
                PopulateTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        Populate_search();
        
    }//GEN-LAST:event_btnsearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnManageFlight;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirliner;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
