/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.OPOWorkArea;

import Buisness.EcoSystem;
import Buisness.Enterprise.Enterprise;
import Buisness.Organization.DonorOrganization;
import Buisness.Organization.LabOrganization;
import Buisness.Organization.Organization;
import Buisness.UserAccount.UserAccount;
import Buisness.WorkQueue.DoctorOrganRequest;
import Buisness.WorkQueue.opoDoctorToDonorRequest;
import Buisness.WorkQueue.opoDoctorToLabRequest;
import Buisness.WorkQueue.workRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patel
 */
public class OPODoctorWorkAreaJpanel extends javax.swing.JPanel {

    /**
     * Creates new form OPODoctorWorkAreaJpanel
     */
    private JPanel container;
    private UserAccount account;
    private Enterprise enterprise;
    private DonorOrganization org;
//    private LabOrganization org1;
    private DonorOrganization org2;
    public OPODoctorWorkAreaJpanel(JPanel container, UserAccount account, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.container = container;
        this.account = account;
        this.enterprise = enterprise;
        PopulateTable();
       // populateDonorTable();
        //populateRequestTable();
        System.out.println(account.getRole().toString());
    }

    public void PopulateTable(){
        
        DefaultTableModel model = (DefaultTableModel) opodoctorJtable.getModel();
        model.setRowCount(0);
        
        for(Organization organization : enterprise.getOrganizationdirectory().getOrganizationList()){
            
            if(organization instanceof DonorOrganization){
                org = (DonorOrganization)organization;
                for(workRequest request : org.getWorkqueue().getWorkrequestList()){
                    DoctorOrganRequest req = (DoctorOrganRequest) request;
                    Object[] row = new Object[5];
                    row[0] = req.getPatient().getName();
                    row[1] = request; 
                    row[2] = req.getDonor();
                    row[3] = request.getResponse();
                    row[4] = req.getStatus();
                    
                    model.addRow(row);
                }
                
            }
        }
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        opodoctorJtable = new javax.swing.JTable();
        txtstatus = new javax.swing.JTextField();
        btnstatus = new javax.swing.JButton();

        jLabel1.setText("Doctor Work Area");

        opodoctorJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Request", "Donor", "Response", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(opodoctorJtable);

        btnstatus.setText("Process Organ Request");
        btnstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(jLabel1)
                        .addGap(0, 490, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnstatus)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstatus))
                .addContainerGap(770, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatusActionPerformed
        
        String status = txtstatus.getText();
        int selectedrow = (int)opodoctorJtable.getSelectedRow();
        Organization organization = null;
        
        for(Organization org1 : enterprise.getOrganizationdirectory().getOrganizationList()){
            
            if(org1 instanceof LabOrganization){
                organization = org1;
                break;
            }  
        }
        
        if(selectedrow>=0){
            
             DoctorOrganRequest req1 = (DoctorOrganRequest)opodoctorJtable.getValueAt(selectedrow, 1);
             req1.setRequest(status);
             req1.setStatus("sendToLab");
//             PopulateTable();
//             JOptionPane.showMessageDialog(null, "Request send succesfully");
             
             try{
                 if(organization!=null){
                     organization.getWorkqueue().getWorkrequestList().add(req1);
                    // account.getWorkqueue().getWorkrequestList().add(req1);
                     
                     PopulateTable();
                     JOptionPane.showMessageDialog(null, "Request send succesfully");
                     //populateRequestTable();
                 }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Can't send Request");
             }
             
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select Row");
        }
        
                
        
    }//GEN-LAST:event_btnstatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable opodoctorJtable;
    private javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables
}
