/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author patel
 */
public class ViewAirlinerJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerJpanel
     */
    private JPanel CardSequenceJpanel;
    private Airliner airliner;
    //private AirlinerDirectory airlinerdirectory;
    
            
    public ViewAirlinerJpanel(JPanel CardSequenceJpanel, Airliner airliner) {
        initComponents();
        this.CardSequenceJpanel=CardSequenceJpanel;
        this.airliner=airliner;
        
        txtName.setText(airliner.getName());
        txtAirid.setText(airliner.getAirlinecode());
        txtNum_f.setText(Integer.toString(airliner.getNumofFlight()));
        //txtC_operated.setText(Integer.toString(airliner.getCountryOperated()));
        txtorigin_c.setText(airliner.getOrigin_country());
        btnSave.setEnabled(false);
        txtName.setEnabled(false);
        txtAirid.setEnabled(false);
        txtNum_f.setEnabled(false);
        //txtC_operated.setEnabled(false);
        txtorigin_c.setEnabled(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        Airliner_id = new javax.swing.JLabel();
        txtAirid = new javax.swing.JTextField();
        Numberofflight = new javax.swing.JLabel();
        txtNum_f = new javax.swing.JTextField();
        origincountry = new javax.swing.JLabel();
        txtorigin_c = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                   VIEW NEW AIRLINER");

        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name");

        txtName.setBackground(new java.awt.Color(153, 153, 153));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        Airliner_id.setForeground(new java.awt.Color(255, 255, 255));
        Airliner_id.setText("Airliner_id");

        txtAirid.setBackground(new java.awt.Color(153, 153, 153));
        txtAirid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAiridActionPerformed(evt);
            }
        });

        Numberofflight.setForeground(new java.awt.Color(255, 255, 255));
        Numberofflight.setText("Number of Flight");

        txtNum_f.setBackground(new java.awt.Color(153, 153, 153));

        origincountry.setForeground(new java.awt.Color(255, 255, 255));
        origincountry.setText("Origin Country");

        txtorigin_c.setBackground(new java.awt.Color(153, 153, 153));
        txtorigin_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorigin_cActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name)
                                    .addComponent(Airliner_id)
                                    .addComponent(Numberofflight)
                                    .addComponent(origincountry))
                                .addGap(145, 145, 145)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(txtAirid)
                                    .addComponent(txtNum_f)
                                    .addComponent(txtorigin_c)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBack))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Airliner_id)
                    .addComponent(txtAirid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numberofflight)
                    .addComponent(txtNum_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origincountry)
                    .addComponent(txtorigin_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAiridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAiridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAiridActionPerformed

    private void txtorigin_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorigin_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorigin_cActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String name=txtName.getText();
        String air_id = txtAirid.getText();
        String origin_c=txtorigin_c.getText();
       // int num_op = Integer.parseInt(txtC_operated.getText());
        //int num_flight = Integer.parseInt(txtNum_flight.getText());
        
        Pattern p = Pattern.compile(" ^[a-zA-Z]+$");
            Matcher m = p.matcher(name);
            Matcher m2 = p.matcher(origin_c);
           Pattern p1 = Pattern.compile("^[a-zA-Z0-9]+$");
            Matcher m1 = p1.matcher(air_id); 
        if(name == null & name == " "){
            
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED));
            Name.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter Name");
            return;
        }/*else if(((m.matches())==false)){
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED));
            Name.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter valid Name");
            return;
        }*/
        else{
            txtName.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            Name.setBackground(Color.BLACK);
        }
        
        if(air_id == null & air_id == " "){
            
            txtAirid.setBorder(BorderFactory.createLineBorder(Color.RED));
            Airliner_id.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter Airliner_id");
            return;
        }else if(((m1.matches())==false)){
            
            txtAirid.setBorder(BorderFactory.createLineBorder(Color.RED));
            Airliner_id.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please valid enter Airliner_id");
            return;
        }
        else{
            txtAirid.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            Airliner_id.setBackground(Color.BLACK);
        }
        
        if(origin_c == null & origin_c == " "){
            
            txtorigin_c.setBorder(BorderFactory.createLineBorder(Color.RED));
            origincountry.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter Origin Country");
            return;
        }else if(((m2.matches())==false)){
             txtorigin_c.setBorder(BorderFactory.createLineBorder(Color.RED));
            origincountry.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter Valid Origin Country");
            return;
        }
        else{
            txtorigin_c.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            origincountry.setBackground(Color.BLACK);
        }
        
       /* try{
            Double.parseDouble(txtC_operated.getText());
            txtC_operated.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            ctot.setForeground(Color.BLACK);
        }
        catch(Exception e){
            txtC_operated.setBorder(BorderFactory.createLineBorder(Color.RED));
            ctot.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter number for Countries operated");
            return;
        }*/
        
        try{
            Double.parseDouble(txtNum_f.getText());
            txtNum_f.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            Numberofflight.setForeground(Color.BLACK);
        }
        catch(Exception e){
            txtNum_f.setBorder(BorderFactory.createLineBorder(Color.RED));
            Numberofflight.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter number for Number of Flights");
            return;
        }
        
        //Airliner airliner = new Airliner();
        airliner.setName(name);
        airliner.setAirlinecode(air_id);
        airliner.setNumofFlight(Integer.parseInt(txtNum_f.getText()));
       // airliner.setCountryOperated(Integer.parseInt(txtC_operated.getText()));
        airliner.setOrigin_country(origin_c);
        //airlinerdirectory.addAirline(airliner);
        JOptionPane.showMessageDialog(null, "Airliner Details Update Sucessfully");
        
        txtName.setEnabled(false);
        txtAirid.setEnabled(false);
        //txtC_operated.setEnabled(false);
        txtNum_f.setEnabled(false);
        txtorigin_c.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        txtName.setEnabled(true);
        txtAirid.setEnabled(true);
        txtNum_f.setEnabled(true);
        //txtC_operated.setEnabled(true);
        txtorigin_c.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        CardSequenceJpanel.remove(this);
        CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        
        Component[] components = CardSequenceJpanel.getComponents();
        for(Component component: components){
            if(component instanceof ManageAirlinersJpanel){
                ManageAirlinersJpanel manage = (ManageAirlinersJpanel) component;
                manage.PopulateTable();
            }
            
        }
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Airliner_id;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Numberofflight;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel origincountry;
    private javax.swing.JTextField txtAirid;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum_f;
    private javax.swing.JTextField txtorigin_c;
    // End of variables declaration//GEN-END:variables
}
