/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.AirplaneDirectory;
import Buisness.Customer;
import Buisness.CustomerDirectory;
import Buisness.FlightDirectory;
import Buisness.Seats;
import UserInterface.Customer.CustomerinformationJpanel;
import UserInterface.ManageAirliners.CreateNewAirlinerJpanel;
import UserInterface.ManageAirliners.ManageAirlinersJpanel;
import UserInterface.TravelAgency.ManageMasterFlightScheduleJPanel;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author patel
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     * 
     */
    private AirlinerDirectory airdirectory;
    private FlightDirectory flightdirectory;
    private CustomerDirectory customerDirectory;
    private AirplaneDirectory airplanedirectory;
    
   // private JPanel CardSequenceJpanel;
    private Seats seat1;
    public TravelAgencyMain() {
 
        initComponents();
        this.airdirectory= new AirlinerDirectory();
        this.flightdirectory = new FlightDirectory();
        this.customerDirectory=new CustomerDirectory();
        this.seat1=new Seats();
        this.airplanedirectory = new AirplaneDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        manageJpanel = new javax.swing.JPanel();
        CardSequenceJpanel = new javax.swing.JPanel();
        btnManage = new javax.swing.JButton();
        btntravelagency = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        manageJpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane2.setLeftComponent(manageJpanel);

        CardSequenceJpanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(CardSequenceJpanel);

        btnManage.setBackground(new java.awt.Color(153, 153, 153));
        btnManage.setText("Manage Airline");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        btntravelagency.setBackground(new java.awt.Color(153, 153, 153));
        btntravelagency.setText("Travel Agency");
        btntravelagency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntravelagencyActionPerformed(evt);
            }
        });

        btnCustomer.setBackground(new java.awt.Color(153, 153, 153));
        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntravelagency, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnManage)
                .addGap(29, 29, 29)
                .addComponent(btntravelagency)
                .addGap(27, 27, 27)
                .addComponent(btnCustomer)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
      
         ManageAirlinersJpanel panel = new ManageAirlinersJpanel(CardSequenceJpanel, airdirectory,airplanedirectory);
        CardSequenceJpanel.add("ManageAirlinersJpanel",panel);
        
        CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        layout.next(CardSequenceJpanel);
        
        /* 
        ManageAirlinersJpanel panel= new ManageAirlinersJpanel(this.CardSequenceJpanel,airdirectory);
        CardSequenceJpanel.add("ManageAirlinersJpanel",panel);
        CardLayout layout = (CardLayout) this.CardSequenceJpanel.getLayout();
        layout.next(CardSequenceJpanel);
        */
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        CardSequenceJpanel.add(new CustomerinformationJpanel(CardSequenceJpanel, CustomerDirectory.customerdirectory));
        layout.next(CardSequenceJpanel);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btntravelagencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntravelagencyActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)CardSequenceJpanel.getLayout();
        CardSequenceJpanel.add(new ManageMasterFlightScheduleJPanel(CardSequenceJpanel,flightdirectory,seat1));
        layout.next(CardSequenceJpanel);
    }//GEN-LAST:event_btntravelagencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJpanel;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btntravelagency;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel manageJpanel;
    // End of variables declaration//GEN-END:variables
}
